### ISSUE TITLE
Không download được data zac2021-ltr-data

### ISSUE THREAD

**Issue by lien19** [phuongnm-bkhn/legal_text_retrieval#1]
Chào bạn,

Link colab của bạn không thể download File như zac2021-ltr-data/legal_corpus.json được nữa. Vậy có cách nào khác để tải dữ liệu về không?
https://colab.research.google.com/github/phuongnm-bkhn/legal_text_retrieval/blob/master/scripts/legal_text_retrieval.ipynb

**Comment by phuongnm94** [comment]
Hiện dl này bên zalo ko public, nên mình gỡ bỏ nó khỏi link github vào k down load trực tiếp được. B có thể liên hệ bên zalo để xin dữ liệu đó phục vụ mục đích nghiên cứu nhé. Hoặc email mình nguyenphuong.cnbt@gmail.com
